version: "3.9"

services:
  siyuan:
    image: b3log/siyuan
    command: ["--workspace=/siyuan/workspace/", "--accessAuthCode=letmein"]
    ports:
      - 6806:6806
    volumes:
      - siyuan_data:/siyuan/workspace
    restart: unless-stopped
    environment:
      - TZ=Europe/Kyiv
      - PUID=1000
      - PGID=1000

volumes:
  siyuan_data:
